### ISSUE TITLE
Exclude std:: functions from fuzz introspector reports

### ISSUE THREAD

**Issue by oliverchang** [ossf/fuzz-introspector#107]
C++ `std::..` calls can be very noisy and likely aren't very useful to fuzzer developers. e.g. for leveldb: https://storage.googleapis.com/oss-fuzz-introspector/leveldb/inspector-report/20220316/calltree_view_0.html 

@Navidem and I discussed this and thought that we should just exclude all of these from the calltree. 

@DavidKorczynski @AdamKorcz WDYT?

**Comment by oliverchang** [comment]
We should also include known libc / other builtin functions. The fuzz blockers list on https://storage.googleapis.com/oss-fuzz-introspector/leveldb/inspector-report/20220316/fuzz_report.html also point to `__clang_call_terminate` and `strlen` as the largest blocked functions, which doesn't seem so useful.

On this note, what exactly is the definition of the "largest blocked function" ?

**Comment by AdamKorcz** [comment]
We have had a discussion about this as well. The same could be said about calls to `free`, `abort`, `exit`, `malloc`, `calloc` etc. In some calltrees these add up to 100+ and will just be noise. And option we considered was to add a button that would allow the user to hide/display these calls.

**Comment by DavidKorczynski** [comment]
> we should just exclude all of these from the calltree.

We actually have support for all this already:
https://github.com/ossf/fuzz-introspector/blob/808f2d4334f831bffce3388d0cbb92e1b6e275b7/post-processing/fuzz_html.py#L657-L663

There is a difference between when/where to include the data -- if we exclude only in the calltree then some analysis may seem wrong as it will be based on another instance of the calltree, i.e. in this case we should block undesired functions at the compiler level to discard it from any data processing -- or improve the data processing pipeline.

However, this problem is bigger than this. The main point is that inevitably users will want to "adjust the data analysed" by fuzz-introspector. The key thing is users may want to "refine the threat model, i.e. refining the source code they are interested in". For example, consider a project (such as Envoy) who builds all of their dependencies as part of the build. This is  going to explode with information that is not interesting to the Envoy developers as such. 

For the more general problem, I have made this: https://github.com/ossf/fuzz-introspector/issues/35

**Comment by DavidKorczynski** [comment]
> On this note, what exactly is the definition of the "largest blocked function" ?

The function with largest cyclomatic complexity amongst all functions that are blocked

**Comment by DavidKorczynski** [comment]
one thing about excluding callsites from the calltree is that it does remove transparency into the code under analysis. I wonder if it would make sense to also try and make them in some form of toned coloring to show they are "not so important". We can perhaps try both and see what works.

**Comment by DavidKorczynski** [comment]
Fixed this one for new -- the solution is to cut off the functions early in the LLVM plugin so they never enter the analysis https://github.com/ossf/fuzz-introspector/pull/115

Long term I think it would make sense moving towards a direction where fuzz-introspector is purely focused on gathering a lot of data and offering analyses, but without being highly opinionated (i.e. removing data) on the exact parameters of the analyses etc but rather allowing the users themselves to choose. But that's many months from now.

**Comment by oliverchang** [comment]
Thanks for addressing this! Re long term making this configurable: completely agree, but we should still have an opinionated default that will work best for the majority of users.

**Comment by david-a-wheeler** [comment]
Good show for the short term, but that option needs to be added - if nothing else, it documents a limitation of the default. I added an issue here for adding an option for more complete analysis: https://github.com/ossf/fuzz-introspector/issues/133
